cmake_minimum_required(VERSION 3.0.2)

option(PACMAKE_PRINT_WARNING "Print PacMake warnings" ON)
option(PACMAKE_PRINT_ERROR "Print PacMake errors" ON)
option(PACMAKE_PRINT_INFO "Print PacMake info" ON)
option(PACMAKE_DEBUG "Print all PacMake messages" OFF)
option(PACMAKE_DEFAULT_SHARED "Build shared libraries by default" OFF)

if(PACMAKE_DEFAULT_SHARED)
	set(PACMAKE_DEFAULT_LIBRARY_TYPE SHARED)
else()
	set(PACMAKE_DEFAULT_LIBRARY_TYPE STATIC)
endif()

set(PACMAKE_BASEDIR ${CMAKE_CURRENT_LIST_DIR} CACHE INTERNAL "PACMAKE_BASEDIR")

if(NOT PACMAKE_PACKAGE_HOME)
	if(DEFINED ENV{HOME})
		set(PACMAKE_PACKAGE_HOME "$ENV{HOME}/.PaCMake" CACHE INTERNAL "PACMAKE_PACKAGE_HOME")
	elseif(DEFINED ENV{USERPROFILE})
		set(PACMAKE_PACKAGE_HOME "$ENV{USERPROFILE}/.PaCMake" CACHE INTERNAL "PACMAKE_PACKAGE_HOME")
	else()
		set(PACMAKE_PACKAGE_HOME "${CMAKE_BINARY_DIR}/PaCMake" CACHE INTERNAL "PACMAKE_PACKAGE_HOME")
	endif()
	
	if(WIN32)
		string(REGEX REPLACE "\\\\" "/" PACMAKE_PACKAGE_HOME "${PACMAKE_PACKAGE_HOME}") #replace windows backslashes
		set(PACMAKE_PACKAGE_HOME "${PACMAKE_PACKAGE_HOME}" CACHE INTERNAL "PACMAKE_PACKAGE_HOME")
	endif()
endif()

function(pacmake_include MODULE)
	include("${PACMAKE_BASEDIR}/module/${MODULE}.cmake")
endfunction(pacmake_include)

pacmake_include(add_package)
