pacmake_include(parse_args)

#pacmake_set_package_property(package version property value)
function(pacmake_set_package_property)
	pacmake_parse_args(args_PACKAGE args_VERSION args_PROPERTY VALUES ${ARGV})
	
	if(NOT args_PACKAGE)
		pacmake_log(ERROR "pacmake_set_package_property(): No package name specified.")
		return()
	elseif(NOT args_VERSION)
		pacmake_log(ERROR "pacmake_set_package_property(${args_PACKAGE}): No package version specified.")
		return()
	elseif(NOT args_PROPERTY)
		pacmake_log(ERROR "pacmake_set_package_property(${args_PACKAGE}, ${args_VERSION}): No package property specified.")
		return()
	elseif(NOT PACMAKE_UNUSED_ARGS)
		pacmake_log(DEFAULT "pacmake_set_package_property(${args_PACKAGE}, ${args_VERSION}, ${args_PROPERTY}): No property value specified.")
		return()
	endif()
	set(PACMAKE_PACKAGE_${args_PACKAGE}_${args_VERSION}_${args_PROPERTY} "${PACMAKE_UNUSED_ARGS}" CACHE INTERNAL "PACMAKE_PACKAGE_${args_PACKAGE}_${args_VERSION}_${args_PROPERTY}")
	
	set(prop_list ${PACMAKE_PACKAGE_PROPERTIES_${args_PACKAGE}_${args_VERSION}})
	list (FIND prop_list "${args_PROPERTY}" i) #IN_LIST only available from cmake 3.3 onward
	if(${i} LESS 0)
		list(APPEND prop_list ${args_PROPERTY})
		set(PACMAKE_PACKAGE_PROPERTIES_${args_PACKAGE}_${args_VERSION} "${prop_list}" CACHE INTERNAL "PACMAKE_PACKAGE_PROPERTIES_${args_PACKAGE}_${args_VERSION}")
	endif()
endfunction(pacmake_set_package_property)

#pacmake_get_package_property(package version property out_value)
function(pacmake_get_package_property args_PACKAGE args_VERSION args_PROPERTY out_value)
	set(${out_value} "${PACMAKE_PACKAGE_${args_PACKAGE}_${args_VERSION}_${args_PROPERTY}}" PARENT_SCOPE)
endfunction(pacmake_get_package_property)

#pacmake_get_property_list(package version out_list)
function(pacmake_get_property_list args_PACKAGE args_VERSION out_list)
	set(key_val_list "")
	foreach(key IN ITEMS ${PACMAKE_PACKAGE_PROPERTIES_${args_PACKAGE}_${args_VERSION}})
		pacmake_get_package_property(${args_PACKAGE} ${args_VERSION} ${key} val)
		list(APPEND key_val_list ${key} ${val})
	endforeach()
	set(${out_list} "${key_val_list}" PARENT_SCOPE)
endfunction(pacmake_get_property_list)
