#pacmake_set_package_property(group package version property value)
function(pacmake_set_package_property args_GROUP args_NAME args_VERSION args_PROPERTY)
	set(args_VALUE ${ARGN})
	if(NOT args_VALUE)
		return()
	endif()
	
	set(PACMAKE_PACKAGE_${args_GROUP}_${args_NAME}_${args_VERSION}_${args_PROPERTY} "${args_VALUE}" CACHE INTERNAL "PACMAKE_PACKAGE_${args_GROUP}_${args_NAME}_${args_VERSION}_${args_PROPERTY}")

	set(prop_list ${PACMAKE_PACKAGE_${args_GROUP}_PROPERTIES_${args_NAME}_${args_VERSION}})
	list(FIND prop_list "${args_PROPERTY}" prop_index)
	if(${prop_index} LESS 0)
		list(APPEND prop_list ${args_PROPERTY})
		set(PACMAKE_PACKAGE_${args_GROUP}_PROPERTIES_${args_NAME}_${args_VERSION} "${prop_list}" CACHE INTERNAL "PACMAKE_PACKAGE_${args_GROUP}_PROPERTIES_${args_NAME}_${args_VERSION}")
	endif()
endfunction(pacmake_set_package_property)

#pacmake_get_package_property(group package version property out_value)
function(pacmake_get_package_property args_GROUP args_NAME args_VERSION args_PROPERTY out_value)
	set(${out_value} "${PACMAKE_PACKAGE_${args_GROUP}_${args_NAME}_${args_VERSION}_${args_PROPERTY}}" PARENT_SCOPE)
endfunction(pacmake_get_package_property)

#pacmake_get_package_properties(group package version out_list)
function(pacmake_get_package_properties args_GROUP args_NAME args_VERSION out_list)
	set(key_val_list "")
	foreach(key IN ITEMS ${PACMAKE_PACKAGE_${args_GROUP}_PROPERTIES_${args_NAME}_${args_VERSION}})
		pacmake_get_package_property(${args_GROUP} ${args_NAME} ${args_VERSION} ${key} val)
		list(APPEND key_val_list ${key} ${val})
	endforeach()
	set(${out_list} "${key_val_list}" PARENT_SCOPE)
endfunction(pacmake_get_package_properties)
