pacmake_include(log)

#pacmake_run_patch(package version [PRECONFIGURE|PREBUILD|POSTBUILD|POSTINSTALL] workdir checkdir)
function(pacmake_run_patch package version type workdir checkdir)
	set(patchdir "${PACMAKE_BASEDIR}/package/${package}/patch")
	
	string(TOLOWER ${type} type_lower)
	if(EXISTS "${checkdir}/patch.${type_lower}")
		pacmake_log(GENERIC "pacmake_run_patch(${package}, ${version}): ${type} patch has already been run, skipping...")
		return()
	elseif(EXISTS "${patchdir}/${type_lower}.cmake")
		file(WRITE "${checkdir}/patch.${type_lower}" "")
		pacmake_log(INFO "pacmake_run_patch(${package}, ${version}): Running ${type} patch...")
		include("${patchdir}/${type_lower}.cmake")
		pacmake_patch(${patchdir} ${workdir} ${package} ${version})
	else()
		pacmake_log(GENERIC "pacmake_run_patch(${package}, ${version}): No ${type} patch to run.")
	endif()
endfunction(pacmake_run_patch)
