pacmake_include(log)

#pacmake_run_patch(patchname version [PRECONFIGURE|PREBUILD|POSTBUILD|POSTINSTALL] package)
function(pacmake_run_patch package version type rootdir workdir)
	set(patchdir "${PACMAKE_BASEDIR}/package/${package}/patch")
	
	if(EXISTS "${rootdir}/patch.${type}")
		pacmake_log(GENERIC "pacmake_run_patch(${package}, ${version}): ${type} patch has already been run, skipping...")
		return()
	endif()
	
	string(TOLOWER ${type} type_lower)
	if(EXISTS "${patchdir}/${type_lower}.cmake")
		pacmake_log(INFO "pacmake_run_patch(${package}, ${version}): Running ${type} patch...")
		include("${patchdir}/${type_lower}.cmake")
		pacmake_patch(${patchdir} ${workdir} ${package} ${version})
		file(WRITE "${rootdir}/patch.${type}" "")
	else()
		pacmake_log(GENERIC "pacmake_run_patch(${package}, ${version}): No ${type} patch to run.")
	endif()
endfunction(pacmake_run_patch)
