# pacmake_textfilefile_read(filePath out_contents)
function(pacmake_textfile_read filePath out_contents)
	file(READ "${filePath}" contents)
	string(REPLACE ";" "@@@___SEMICOLON___@@@" contents "${contents}")
	string(REPLACE "[" "@@@___SQUARE_BRACKET_OPEN___@@@" contents "${contents}")
	string(REPLACE "]" "@@@___SQUARE_BRACKET_CLOSE___@@@" contents "${contents}")
	set(${out_contents} ${contents} PARENT_SCOPE)
endfunction(pacmake_textfile_read)

# pacmake_textfilefile_write(filePath contents)
function(pacmake_textfile_write filePath)
	string(REPLACE ";" "" contents "${ARGN}")
	string(REPLACE "@@@___SQUARE_BRACKET_CLOSE___@@@" "]" contents "${contents}")
	string(REPLACE "@@@___SQUARE_BRACKET_OPEN___@@@" "[" contents "${contents}")
	string(REPLACE "@@@___SEMICOLON___@@@" ";" contents "${contents}")
	file(WRITE "${filePath}" "${contents}")
endfunction(pacmake_textfile_write)

# pacmake_textfile_replace(filePath origString replaceString)
function(pacmake_textfile_replace filePath origString replaceString)
	string(REPLACE ";" "@@@___SEMICOLON___@@@" origString "${origString}")
	string(REPLACE "[" "@@@___SQUARE_BRACKET_OPEN___@@@" origString "${origString}")
	string(REPLACE "]" "@@@___SQUARE_BRACKET_CLOSE___@@@" origString "${origString}")
	
	string(REPLACE ";" "@@@___SEMICOLON___@@@" replaceString "${replaceString}")
	string(REPLACE "[" "@@@___SQUARE_BRACKET_OPEN___@@@" replaceString "${replaceString}")
	string(REPLACE "]" "@@@___SQUARE_BRACKET_CLOSE___@@@" replaceString "${replaceString}")
	
	pacmake_textfile_read("${filePath}" contents)
	string(REPLACE "${origString}" "${replaceString}" contents ${contents})
	pacmake_textfile_write("${filePath}" "${contents}")
endfunction(pacmake_textfile_replace)
