# pacmake_textfile_replace(outputFilePath inputFilePath [STRING orig1 replacement1 [...]] [REGEX pattern1 replacement1 [...]])
function(pacmake_textfile_replace outputFilePath inputFilePath)
	file(READ "${inputFilePath}" contents)

	set(type "")
	set(i 2)
	set(orig "")
	while(i LESS ARGC)
		set(arg "${ARGV${i}}")
		math(EXPR i "${i} + 1")

		if(arg MATCHES "STRING|REGEX")
			set(type "${arg}")
			continue()
		elseif(NOT type)
			message(FATAL_ERROR "Unknown replacement type: must be either STRING OR REGEX.")
		endif()

		if(NOT orig)
			set(orig "${arg}")
			continue()
		endif()

		if(type STREQUAL REGEX)
			string(REGEX REPLACE "${orig}" "${arg}" contents "${contents}")
		else()
			string(REPLACE "${orig}" "${arg}" contents "${contents}")
		endif()
		set(orig "")
	endwhile()

	file(WRITE "${outputFilePath}" "${contents}")
endfunction(pacmake_textfile_replace)
