function(pacmake_patch packageName packageVersion workingDirectory)
	file(COPY "${PACMAKE_HOME}/package/imgui/${packageVersion}/src/orig/backends/imgui_impl_vulkan.h" DESTINATION "${workingDirectory}/")
	file(COPY "${PACMAKE_HOME}/package/imgui/${packageVersion}/src/orig/backends/imgui_impl_vulkan.cpp" DESTINATION "${workingDirectory}/")
	
	file(WRITE "${workingDirectory}/CMakeLists.txt"
		"cmake_minimum_required(VERSION 3.5)\n"
		"\n"
		"project(imgui-backend-vulkan LANGUAGES CXX VERSION ${packageVersion})\n"
		"\n"
		"file(GLOB SOURCES \"*.cpp\")\n"
		"file(GLOB HEADERS \"*.h\")\n"
		"add_library(\${PROJECT_NAME} \${SOURCES} \${HEADERS})\n"
		"\n"
		"find_package(imgui REQUIRED)\n"
		"find_package(Vulkan REQUIRED)\n"
		"target_link_libraries(\${PROJECT_NAME} PUBLIC imgui::imgui Vulkan::Vulkan)\n"
		"\n"
		"include(GNUInstallDirs)\n"
		"\n"
		"install(\n"
		"\tTARGETS \${PROJECT_NAME}\n"
		"\tEXPORT \"\${PROJECT_NAME}Targets\"\n"
		"\tLIBRARY DESTINATION \"\${CMAKE_INSTALL_LIBDIR}\"\n"
		"\tARCHIVE DESTINATION \"\${CMAKE_INSTALL_LIBDIR}\"\n"
		"\tRUNTIME DESTINATION \"\${CMAKE_INSTALL_BINDIR}\"\n"
		"\tINCLUDES DESTINATION \"\${CMAKE_INSTALL_INCLUDEDIR}\"\n"
		")\n"
		"\n"
		"install(\n"
		"\tFILES \${HEADERS}\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_INCLUDEDIR}\"\n"
		")\n"
		"\n"
		"include(CMakePackageConfigHelpers)\n"
		"\n"
		"write_basic_package_version_file(\n"
		"\t\"\${CMAKE_BINARY_DIR}/\${PROJECT_NAME}ConfigVersion.cmake\"\n"
		"\tVERSION \${PROJECT_VERSION}\n"
		"\tCOMPATIBILITY AnyNewerVersion\n"
		")\n"
		"\n"
		"install(\n"
		"\tFILES \"\${CMAKE_BINARY_DIR}/\${PROJECT_NAME}ConfigVersion.cmake\"\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_LIBDIR}/cmake/\${PROJECT_NAME}\"\n"
		")\n"
		"\n"
		"install(\n"
		"\tEXPORT \"\${PROJECT_NAME}Targets\"\n"
		"\tFILE \"\${PROJECT_NAME}Config.cmake\"\n"
		"\tNAMESPACE \"imgui::\"\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_LIBDIR}/cmake/\${PROJECT_NAME}\"\n"
		")\n"
	)
endfunction(pacmake_patch)
