pacmake_include(log)
pacmake_include(textfile)

function(pacmake_patch patchdir workdir package version)
	set(cmake_dir "${workdir}/install/lib/cmake")
	if(EXISTS ${cmake_dir})
		file(RENAME "${cmake_dir}/SDL2" "${cmake_dir}/SDL2_ttf")
		set(target_dir "${cmake_dir}/SDL2_ttf")
	elseif(EXISTS "${workdir}/install/cmake")
		set(target_dir "${workdir}/install/cmake")
	endif()
	if(target_dir)
		pacmake_textfile_replace("${target_dir}/SDL2_ttfConfig.cmake" "/SDL2_TTFTargets.cmake" "/SDL2_ttfTargets.cmake")
	endif()
endfunction(pacmake_patch)
