
function(pacmake_patch packageName packageVersion workingDirectory)
	file(WRITE "${workingDirectory}/CMakeLists.txt"
		"cmake_minimum_required(VERSION 3.11)\n"
		"\n"
		"project(imgui LANGUAGES CXX VERSION ${packageVersion})\n"
		"\n"
		"file(GLOB SOURCES \"*.cpp\")\n"
		"file(GLOB HEADERS \"*.h\")\n"
		"add_library(\${PROJECT_NAME} \${SOURCES} \${HEADERS})\n"
		"add_executable(\"binary_to_compressed_c\" \"misc/fonts/binary_to_compressed_c.cpp\")\n"
		"\n"
		"include(GNUInstallDirs)\n"
		"\n"
		"install(\n"
		"\tTARGETS \${PROJECT_NAME}\n" \"binary_to_compressed_c\"
		"\tEXPORT \"\${PROJECT_NAME}Targets\"\n"
		"\tLIBRARY DESTINATION \"\${CMAKE_INSTALL_LIBDIR}\"\n"
		"\tARCHIVE DESTINATION \"\${CMAKE_INSTALL_LIBDIR}\"\n"
		"\tRUNTIME DESTINATION \"\${CMAKE_INSTALL_BINDIR}\"\n"
		"\tINCLUDES DESTINATION \"\${CMAKE_INSTALL_INCLUDEDIR}\"\n"
		")\n"
		"\n"
		"install(\n"
		"\tFILES \${HEADERS}\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_INCLUDEDIR}\"\n"
		")\n"
		"\n"
		"include(CMakePackageConfigHelpers)\n"
		"\n"
		"write_basic_package_version_file(\n"
		"\t\"\${CMAKE_BINARY_DIR}/${packageName}ConfigVersion.cmake\"\n"
		"\tVERSION \${PROJECT_VERSION}\n"
		"\tCOMPATIBILITY AnyNewerVersion\n"
		")\n"
		"\n"
		"install(\n"
		"\tFILES \"\${CMAKE_BINARY_DIR}/${packageName}ConfigVersion.cmake\"\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_LIBDIR}/cmake/${packageName}\"\n"
		")\n"
		"\n"
		"install(\n"
		"\tEXPORT \"\${PROJECT_NAME}Targets\"\n"
		"\tFILE \"${packageName}Config.cmake\"\n"
		"\tNAMESPACE \"imgui-docking::\"\n"
		"\tDESTINATION \"\${CMAKE_INSTALL_LIBDIR}/cmake/${packageName}\"\n"
		")\n"
	)
endfunction(pacmake_patch)
